# Generated by Django 4.2 on 2025-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_farmerprofile_crops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agronomist', 'Agronomist'), ('extension_officer', 'Extension Officer')], default='farmer', max_length=20),
        ),
    ]
