# Generated by Django 4.2 on 2025-06-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_farmerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerprofile',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('agronomist', 'Agronomist'), ('extension officer', 'Extension Officer')], default='farmer', max_length=20),
        ),
    ]
